Updates
PatrickWhitehouse/AD-11ty pull request #4
Opened 2021-09-24 19:32 UTC by Joey690152

Updated colours for Nav as well as removing underline and adding a border bottom instead... hopefully to use a nice effect later on in the styling process

2021-09-24 19:59 UTC, PatrickWhitehouse requested changes
Added a note to that file

2021-09-24 19:59 UTC, PatrickWhitehouse commented on src/css/tailwind.css
> +  text-decoration-thickness: 3px;
I'd remove 7 & 8 too.

2021-09-24 20:39 UTC, Joey690152 commented on src/css/tailwind.css
> +  text-decoration-thickness: 3px;
No problem. i will do tomorrow

2021-09-25 13:53 UTC, Joey690152 commented on src/css/tailwind.css
> +  text-decoration-thickness: 3px;
i believe this has now been amended correctly.

2021-09-28 20:13 UTC, PatrickWhitehouse approved these changes
Nice one.

2021-09-28 20:15 UTC, merged